### ISSUE TITLE
ValueError: Semaphore released too many times

### ISSUE THREAD

**Issue by nudomarinero** [lofar-astron/prefactor#11]
I get this error. I am not sure if this is a problem with the generic pipeline, the recipe or my system.
Any hint?
```
2016-03-20 16:21:50 WARNING genericpipeline.executable_args: Remote command stderr: /opt/LofIm-2_15/lib/python2.7/site-packages/lofar/parmdb/__init__.py:22: RuntimeWarning: to-Python converter for std::vector<double, std::allocator<double> > already registered; second conversion method ignored.
  from _parmdb import ParmDB
/opt/LofIm-2_15/lib/python2.7/site-packages/lofar/parmdb/__init__.py:22: RuntimeWarning: to-Python converter for std::vector<std::string, std::allocator<std::string> > already registered; second conversion method ignored.
  from _parmdb import ParmDB

Exception in thread Thread-198:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/LofIm-2_15/lib/python2.7/site-packages/lofarpipe/support/remotecommand.py", line 296, in dispatch
    limiter[self.host].release()
  File "/usr/lib/python2.7/threading.py", line 536, in release
    raise ValueError("Semaphore released too many times")
ValueError: Semaphore released too many times

2016-03-20 16:21:51 ERROR   genericpipeline.executable_args: A job has failed and error_tolerance is not set. Bailing out!
2016-03-20 16:21:51 WARNING genericpipeline.executable_args: Note: recipe outputs are not complete
2016-03-20 16:21:51 WARNING genericpipeline.executable_args: recipe executable_args completed with errors
2016-03-20 16:21:51 WARNING genericpipeline: pythonplugin reports failure (using executable_args recipe)
2016-03-20 16:21:51 ERROR   genericpipeline: *******************************************
2016-03-20 16:21:51 ERROR   genericpipeline: Failed pipeline run: Pre-Facet-Pretarget
2016-03-20 16:21:51 ERROR   genericpipeline: Detailed exception information:
2016-03-20 16:21:51 ERROR   genericpipeline: <class 'lofarpipe.support.lofarexceptions.PipelineRecipeFailed'>
2016-03-20 16:21:51 ERROR   genericpipeline: pythonplugin failed
2016-03-20 16:21:51 ERROR   genericpipeline: *******************************************
2016-03-20 16:21:51 ERROR   genericpipeline: LOFAR Pipeline finished unsuccesfully.
2016-03-20 16:21:51 WARNING genericpipeline: recipe genericpipeline completed with errors
```

**Comment by twshimwell** [comment]
This issue was also noticed the other day and Andreas issued a LOFAR bug-tracker report about it... cant seem to find the link for it though.

**Comment by nudomarinero** [comment]
Yes, the problem seems to be reported in: https://support.astron.nl/lofar_issuetracker/issues/9210

**Comment by AHorneffer** [comment]
As I wrote on the bug-tracker, I believe that this is a problem of the pipeline framework. (In a part of said framework that IMHO needs re-writing anyhow.)

So I guess we can close the issue here.
