### ISSUE TITLE
How to set up pipeline.cfg when using kern lofar package?

### ISSUE THREAD

**Issue by mknapp55** [lofar-astron/prefactor#127]
Hi,

I'm trying to get prefactor running on my own machine.  I've installed lofar and other relevant packages from the Kern-2 ppa repository.  What's the appropriate way to set up the pipeline.cfg file in this case?  Specifically, how should I set the lofarroot, casaroot, pyraproot, etc.?  I tried leaving all of those entries blank, but I got errors like the one below:
`ubuntu@ip-100-64-109-221:/data/t1data$ genericpipeline.py -d -v -c pipeline.cfg PFC_t1.parset 
/usr/lib/python2.7/dist-packages/lofarpipe/support/utilities.pyc : Using default subprocess module!
QPID support NOT enabled! Will NOT connect to any broker, and messages will be lost!
Reading configuration file: pipeline.cfg
***** Exception occurred with no log handlers
***** ['/share/pipeline/tasks.cfg'] is an invalid value for FileList task_files
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/lofarpipe/cuisine/WSRTrecipe.py", line 132, in run
    status = self.go()
  File "/usr/bin/genericpipeline.py", line 97, in go
    return super(GenericPipeline, self).go()
  File "/usr/lib/python2.7/dist-packages/lofarpipe/support/control.py", line 129, in go
    super(control, self).go()
  File "/usr/lib/python2.7/dist-packages/lofarpipe/support/stateful.py", line 91, in go
    super(StatefulRecipe, self).go()
  File "/usr/lib/python2.7/dist-packages/lofarpipe/support/baserecipe.py", line 221, in go
    self.config.get('DEFAULT', "task_files")
  File "/usr/lib/python2.7/dist-packages/lofarpipe/support/lofaringredient.py", line 252, in __setitem__
    (str(value), type(field).__name__, key)
TypeError: ['/share/pipeline/tasks.cfg'] is an invalid value for FileList task_files
No results
`

**Comment by nudomarinero** [comment]
Hello, I use the generic pipeline using Kern and do not have this problem. I do not need to set the variables that you mention and it works straight away but I might be using a previous version of Kern. I think that the root path should be set to "/usr". Let me know if that works. If not, I could try to reproduce the error in a Virtual Machine to find the origin of the problem.

**Comment by AHorneffer** [comment]
`lofarroot`, `casaroot`, `pyraproot`, etc. should be set by the installer of the LOFAR software. `casaroot` might not be needed, but it won't work without  `lofarroot` and any of the other `*root` paths that are referenced in the config file.

Does the Kern package include a the file: `$LOFARROOT/share/pipeline/pipeline.cfg` and are these values set in there?

**Comment by mknapp55** [comment]
@AHorneffer I did find the pipeline.cfg file from the Kern package installation (LOFARROOT is /usr).  I modified it as usual (runtime and working directories, logfile locations), fixed a problem with my python path, and got a bit farther.  I'm now running into a problem with DPPP.  I checked that both the commandline executable (DPPP/NDPPP) works and that I can also import it in python (lofar.dppp), so I'm fairly convinced it's correctly installed.  I also checked that the recipe directory exists on the path specified and that the necessary files are there.

`ubuntu@ip-100-64-109-221:/data/t1data/run_L556822/PFC_t1/logs/2017-04-03T15:24:28$ cat pipeline.log 
2017-04-03 15:24:28 INFO    genericpipeline: LOFAR Pipeline (PFC_t1) starting.
2017-04-03 15:24:28 INFO    genericpipeline: SASID = , MOMID = , Feedback method = none
2017-04-03 15:24:28 INFO    genericpipeline: Beginning step createmap_cal
2017-04-03 15:24:28 INFO    genericpipeline: Beginning step ndppp_prep_cal
2017-04-03 15:24:28 INFO    genericpipeline: Running task: dppp
2017-04-03 15:24:28 INFO    genericpipeline.executable_args: recipe executable_args started
2017-04-03 15:24:28 INFO    genericpipeline.executable_args: Starting /usr/bin/NDPPP run
2017-04-03 15:24:28 INFO    genericpipeline.executable_args: Limiting to 8 simultaneous jobs/node
2017-04-03 15:24:28 ERROR   genericpipeline.executable_args: Exception caught: [Errno -2] Name or service not known
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/lofarpipe/cuisine/WSRTrecipe.py", line 132, in run
    status = self.go()
  File "/usr/lib/python2.7/dist-packages/lofarpipe/recipes/master/executable_args.py", line 387, in go
    self._schedule_jobs(jobs, max_per_node)
  File "/usr/lib/python2.7/dist-packages/lofarpipe/support/remotecommand.py", line 449, in _schedule_jobs
    with job_server(self.logger, jobpool, self.error) as (jobhost, jobport):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/lib/python2.7/dist-packages/lofarpipe/support/jobserver.py", line 169, in job_server
    jobserver = JobSocketReceiver(logger, jobpool, error, port=0)
  File "/usr/lib/python2.7/dist-packages/lofarpipe/support/jobserver.py", line 113, in __init__
    SocketServer.ThreadingTCPServer.__init__(self, (host, port), JobStreamHandler)
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
gaierror: [Errno -2] Name or service not known
2017-04-03 15:24:28 WARNING genericpipeline: dppp reports failure (using executable_args recipe)
2017-04-03 15:24:28 ERROR   genericpipeline: *******************************************
2017-04-03 15:24:28 ERROR   genericpipeline: Failed pipeline run: PFC_t1
2017-04-03 15:24:28 ERROR   genericpipeline: Detailed exception information:
2017-04-03 15:24:28 ERROR   genericpipeline: <class 'lofarpipe.support.lofarexceptions.PipelineRecipeFailed'>
2017-04-03 15:24:28 ERROR   genericpipeline: dppp failed
2017-04-03 15:24:28 ERROR   genericpipeline: *******************************************
2017-04-03 15:24:28 ERROR   genericpipeline: LOFAR Pipeline finished unsuccesfully.
2017-04-03 15:24:28 WARNING genericpipeline: recipe genericpipeline completed with errors`

**Comment by AHorneffer** [comment]
```
File "/usr/lib/python2.7/socket.py", line 228, in meth return getattr(self._sock,name)(*args) 
gaierror: [Errno -2] Name or service not known
```
Looks like something is wrong with your system setup.  (It didn't get as far as starting NDPPP, it only says "dppp failed" because it failed while trying to run the task called "dppp".)

Can you run these lines in Python (with the same Python-paths as the pipeline):
```
import socket
socket.getaddrinfo(socket.gethostname(),12345)
socket.getaddrinfo('localhost',12345)
```

**Comment by mknapp55** [comment]
See below.  FWIW, this is an AWS machine, but it should work just like any other ubuntu machine.

`In [1]: import socket

In [2]: socket.getaddrinfo(socket.gethostname(),12345)
---------------------------------------------------------------------------
gaierror                                  Traceback (most recent call last)
<ipython-input-2-4b1be891713c> in <module>()
----> 1 socket.getaddrinfo(socket.gethostname(),12345)

gaierror: [Errno -2] Name or service not known

In [3]: socket.getaddrinfo('localhost',12345)
Out[3]: 
[(2, 1, 6, '', ('127.0.0.1', 12345)),
 (2, 2, 17, '', ('127.0.0.1', 12345)),
 (2, 3, 0, '', ('127.0.0.1', 12345))]
`

**Comment by AHorneffer** [comment]
So, indeed your name-service is not correctly set up.
If you ask you machine what name it has (`socket.gethostname()`), and then as it which IP-address is associated with that name (`socket.getaddrinfo()`) it tells you that it doesn't know that name.

**Comment by mknapp55** [comment]
I'll talk to the sysadmin who set up the AWS machine.  Just for my information, why does prefactor or dppp care what the name of the machine is?

**Comment by AHorneffer** [comment]
@mknapp55 Because the underlying pipeline framework does.
(It is actually useful if you also have processes running on other machines.)

**Comment by AHorneffer** [comment]
(As in: if you want to start processes on other machines, and want them to talk to you.)
