### ISSUE TITLE
Which losoto to use on CEP3?

### ISSUE THREAD

**Issue by mknapp55** [lofar-astron/prefactor#128]
I got an error when using the losoto executable from a recent build (/opt/cep/losoto/losoto-master-20170327/bin/losoto) [below], so I switched to the current losoto on CEP3 (/opt/cep/losoto/current/bin/losoto) and got a different error at the same spot.  Which one should I be using?

First try:
`2017-04-03 17:56:10 INFO    node.lof002.executable_args: Processing ./h5imp_cal_losoto.h5
2017-04-03 17:56:10 WARNING node.lof002.executable_args.h5imp_cal_losoto.h5: /opt/cep/losoto/losoto-master-20170327/bin/losoto stderr: Traceback (most recent call last):
  File "/opt/cep/losoto/losoto-master-20170327/bin/losoto", line 4, in <module>
    __import__('pkg_resources').run_script('losoto==0.5', 'losoto')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3084, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3070, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3097, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 653, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 666, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 839, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'losoto==0.5' distribution was not found and is required by the application

2017-04-03 17:56:13 ERROR   node.lof002.executable_args: Command '/opt/cep/losoto/losoto-master-20170327/bin/losoto' returned non-zero exit status 1`

Second try:
`2017-04-03 18:11:03 INFO    node.lof002.executable_args: Processing ./h5imp_cal_losoto.h5
2017-04-03 18:11:04 WARNING node.lof002.executable_args.h5imp_cal_losoto.h5: /opt/cep/losoto/current/bin/losoto stderr: log4cplus:ERROR No appenders could be found for logger (LCS.Common.EXCEPTION).
log4cplus:ERROR Please initialize the log4cplus system properly.
Traceback (most recent call last):
  File "/opt/cep/losoto/current/bin/losoto", line 4, in <module>
    __import__('pkg_resources').run_script('losoto==1.0.0', 'losoto')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1652, in run_script
    exec(code, namespace, namespace)
  File "/opt/cep/losoto/losoto-master-20160704/lib/python2.7/site-packages/losoto-1.0.0-py2.7.egg/EGG-INFO/scripts/losoto", line 99, in <module>
    parset = lofar.parameterset.parameterset( parsetFile )
  File "/opt/cep/lofar/lofar_versions/LOFAR-Release-2_15_2/lofar_build/install/gnu_opt/lib/python2.7/site-packages/lofar/parameterset/__init__.py", line 93, in __init__
    PyParameterSet.__init__ (self, filename, caseInsensitive);
RuntimeError: Assertion: pos != string::npos; Unbalanced quoted string at position 4471 in 

2017-04-03 18:11:07 ERROR   node.lof002.executable_args: Command '/opt/cep/losoto/current/bin/losoto' returned non-zero exit status 1
`

**Comment by AHorneffer** [comment]
The first error looks like a problem with the  `$PYTHONPATH`. 

The second error is because you use an old version of the LOFAR software: 2.15.2, which  is more than a year old! We are now at version 2.20, prefactor requires at least version 2.17. (And if you'd fix the `$PYTHONPATH` for the other LoSoTo version, then you'd get the same error.)

**Comment by mknapp55** [comment]
Can you advise on how to set up the pipeline.cfg?  I followed the instructions on the wiki and copied the pipeline.cfg in $LOFARROOT/share/pipeline/pipeline.cfg and modified the runtime and working directories.  That file (and CEP3 lof002) has $LOFARROOT=/opt/cep/lofar/lofar_versions/LOFAR-Release-2_15_2/lofar_build/install/gnu_opt

I tried replacing the lofarroot parameter (and pythonpath) in pipeline.cfg with the daily build and with Release-2_20_0, but I got an error in both cases.

`2017-04-04 21:49:08 INFO    genericpipeline.executable_args: Starting /opt/cep/lofar/lofar_versions/LOFAR-Release-2_20_0/lofar_build/install/gnu_opt/bin/NDPPP run
Reading configuration file: pipeline.cfg
Reading task definition file(s): /opt/cep/lofar/lofar_versions/LOFAR-Release-2_20_0/lofar_build/install/gnu_opt/share/pipeline/tasks.cfg
2017-04-04 21:49:08 DEBUG   genericpipeline.executable_args: Pipeline start time: 2017-04-04T21:49:08
2017-04-04 21:49:08 ERROR   genericpipeline.executable_args: Exception caught: __init__() got an unexpected keyword argument 'resources'
Traceback (most recent call last):
  File "/opt/cep/lofar/lofar_versions/LOFAR-Release-2_15_2/lofar_build/install/gnu_opt/lib/python2.7/site-packages/lofarpipe/cuisine/WSRTrecipe.py", line 132, in run
    status = self.go()
  File "/opt/cep/lofar/lofar_versions/LOFAR-Release-2_20_0/lofar_build/install/gnu_opt/lib/python2.7/site-packages/lofarpipe/recipes/master/executable_args.py", line 382, in go
    "cores": self.inputs['nthreads']
TypeError: __init__() got an unexpected keyword argument 'resources'
2017-04-04 21:49:08 WARNING genericpipeline: dppp reports failure (using executable_args recipe)
2017-04-04 21:49:08 ERROR   genericpipeline: *******************************************
2017-04-04 21:49:08 ERROR   genericpipeline: Failed pipeline run: PFC_t1_L556830
2017-04-04 21:49:08 ERROR   genericpipeline: Detailed exception information:
2017-04-04 21:49:08 ERROR   genericpipeline: <class 'lofarpipe.support.lofarexceptions.PipelineRecipeFailed'>
2017-04-04 21:49:08 ERROR   genericpipeline: dppp failed
2017-04-04 21:49:08 ERROR   genericpipeline: *******************************************
2017-04-04 21:49:08 ERROR   genericpipeline: LOFAR Pipeline finished unsuccesfully.
2017-04-04 21:49:08 WARNING genericpipeline: recipe genericpipeline completed with errors
`

**Comment by AHorneffer** [comment]
You are mixing code from version 2.15.2 with code from version 2.20.0.

I don't use CEP3 myself, but I guess you would need to
- start from a clean environment
- load the LOFAR environment with something like: `use Lofar LOFAR-Release-2_20_0`
- copy the `$LOFARROOT/share/pipeline/pipeline.cfg` 
- continue as documented

P.S. I agree that the setup on CEP3 is a bit of a mess. Feel free to complain to ASTRON to set up an easier to understand setup and/or document it better.
P.P.S. When pasting lots of pre-formatted code into github then please use three backtics on a separate line as start- and end-marker.

**Comment by tammojan** [comment]
Astron is planning to upgrade the cep3 software end May, hopefully things will be easier then.

**Comment by mknapp55** [comment]
Thanks @AHorneffer - it turns out I had a line in my .mypackages which was forcing me to use release 2_15.  I fixed that and prefactor is running now.  I'll close this ticket.
