### ISSUE TITLE
ERROR INITIAL SUBTRACTION

### ISSUE THREAD

**Issue by MarisaBrienza** [lofar-astron/prefactor#129]
@ygrange  @shulevski

The initial subtraction crashes with these errors and we cannot find the reason. do you have any ideas? I attach here the full log
[log_subtract_marisa_13april.txt](https://github.com/lofar-astron/prefactor/files/919592/log_subtract_marisa_13april.txt)

2017-04-12 18:36:26 ERROR   node.flits-05.python_plugin: index -9223372036854775808 is out of bounds for axis 0 with size 8
[..]
2017-04-12 19:37:38 ERROR   node.flits-05.executable_args: Command '/bin/cp' returned non-zero exit status 1
[..]
2017-04-12 19:37:38 ERROR   genericpipeline.executable_args: Remote process python /home/brienza/software/lofar_soft_Yan/lofarsoft-2_18/lib/python2.7/site-packages/lofarpipe/recipes/nodes/executable_args.py ['/home/brienza/4C1250_cycle5/working/Initial-Subtract/L452678_SB000_uv.dppp_1281ACBB9t_144MHz.wsclean_high1-image.mask_high', '/bin/cp', ['/home/brienza/4C1250_cycle5/working/Initial-Subtract/L452678_SB000_uv.dppp_1281ACBB9t_142MHz.wsclean_high1-image.mask_high', '/home/brienza/4C1250_cycle5/inspection_directory/'], {}, '/home/brienza/4C1250_cycle5/working/Initial-Subtract', False, {'args_format_option_argument': '=', 'args_format_option': '-', 'args_format': 'gnu', 'args_formatlongoption': '--', 'args_format_argument': ''}, {'KARMASTATICLIBPATH': '/usr/local/karma/karma/static-lib', 'LOFARDATAROOT': '/opt/lofar/data', 'OMP_NUM_THREADS': '8', 'PYTHONPATH': '/home/brienza/software/lofar_soft_Yan/lofarsoft-2_18/lib/python2.7/site-packages', 'KARMABINPATH': '/usr/local/karma/karma/bin', 'KARMAINCLUDEPATH': '/usr/local/karma/karma/include', 'LOFARROOT': '/home/brienza/software/lofar_soft_Yan/lofarsoft-2_18', 'KARMALIBPATH': '/usr/local/karma/karma/lib', 'PATH': '/home/brienza/software/lofar_soft_Yan/lofarsoft-2_18/sbin:/home/brienza/software/lofar_soft_Yan/lofarsoft-2_18/bin:/usr/local/MUSE/bin/:/usr/local/karma/karma/cm_script:/usr/local/karma/karma/csh_script:/usr/local/karma/karma/site/i386_Linux/bin:/usr/local/karma/karma/bin:/usr/local/karma/karma/bin:/usr/local/miriad/opt/bin:/usr/local/miriad/bin/linux:/usr/local/casapy-4.2.1/bin:/usr/local/MUSE/bin/:/usr/local/karma/karma/cm_script:/usr/local/karma/karma/csh_script:/usr/local/karma/karma/site/i386_Linux/bin:/usr/local/karma/karma/bin:/usr/local/karma/karma/bin:/usr/local/miriad/opt/bin:/usr/local/miriad/bin/linux:/usr/local/casapy-4.2.1/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/stow/c3-5.1.3/usr/bin:/usr/local/losoto/tools:/usr/local/losoto:/usr/lib/jvm/java-1.7.0-openjdk-amd64/:/usr/local/losoto/tools:/usr/local/losoto:/usr/lib/jvm/java-1.7.0-openjdk-amd64/', 'LD_LIBRARY_PATH': '/home/brienza/software/lofar_soft_Yan/lofarsoft-2_18/lib'}] failed on localhost
[..]
2017-04-12 19:37:42 ERROR   genericpipeline.executable_args: Exception caught: list index out of range
Traceback (most recent call last):
  File "/home/brienza/software/lofar_soft_Yan/lofarsoft-2_18/lib/python2.7/site-packages/lofarpipe/cuisine/WSRTrecipe.py", line 132, in run
    status = self.go()
  File "/home/brienza/software/lofar_soft_Yan/lofarsoft-2_18/lib/python2.7/site-packages/lofarpipe/recipes/master/executable_args.py", line 364, in go
    parsetdict_copy[k] = value[i]
IndexError: list index out of range
2017-04-12 19:37:42 WARNING genericpipeline: executable_args reports failure (using executable_args recipe)
2017-04-12 19:37:42 ERROR   genericpipeline: *******************************************
2017-04-12 19:37:42 ERROR   genericpipeline: Failed pipeline run: Initial-Subtract
2017-04-12 19:37:42 ERROR   genericpipeline: Detailed exception information:
2017-04-12 19:37:42 ERROR   genericpipeline: <class 'lofarpipe.support.lofarexceptions.PipelineRecipeFailed'>
2017-04-12 19:37:42 ERROR   genericpipeline: executable_args failed
2017-04-12 19:37:42 ERROR   genericpipeline: *******************************************
2017-04-12 19:37:42 ERROR   genericpipeline: LOFAR Pipeline finished unsuccesfully.
2017-04-12 19:37:42 WARNING genericpipeline: recipe genericpipeline completed with errors

**Comment by ygrange** [comment]
We did check is whether there is some issue with PTHONPATH or LD_LIBRARY_PATH but that wasn't limited. The install procedure can be found [here](https://github.com/lofar-astron/lofar-deploy/tree/master/contributions/flits).

**Comment by AHorneffer** [comment]
(The snippets from the logfile that you pasted here are useless and misleading, so I suggest not to add them. But you did upload the logfile, so I could have a look.)

It is actually `pyBDSM` called from `make_clean_mask.py` that fails first. 

Did you set `error_tolerance` to `True` in the pipeline parset? (I just saw, that the documentation for that needs to be updated. You should leave that at `False` unless you really know what you are doing.)

The actual error message of pyBDSM is:
```
2017-04-12 18:36:26 ERROR   node.flits-05.python_plugin: index -9223372036854775808 is out of bounds for axis 0 with size 8
```
And `-9223372036854775808` is `-0x8000000000000000` (i.e. a 64-bit integer with only the most-significant-bit (which is the sign bit in a signed integer) set) which looks suspiciously like an integer overflow or some other nasty bit-manipulation somewhere. 

Hmmmm... did you check if the machine ran out of memory?

**Comment by ygrange** [comment]
Since we use LOFAR 2.18, we don't externally build PyBDSM/F since that wasn't externalised by then. Would it be sensible to try using an external version?

If I check the Ganglia of the cluster, it looks like the system didn't have issues with regard to memory. However, the system load is completely through the roof, and that seems unrelated to @MarisaBrienza 's processing. I am not sure if this causes this crash, but we may want to confirm if this happens on another node too...

**Comment by AHorneffer** [comment]
@ygrange It looks to me like a problem with the software on your system in one way or another (out of memory, incompatible libraries, or something else). Can you check that?
You can also try to run the `make_clean_mask.py` manually outside of the pipeline.

**Comment by AHorneffer** [comment]
I guess this one is solved. Please re-open if needed.
