### ISSUE TITLE
problem running genericpipeline.py on a new cluster

### ISSUE THREAD

**Issue by lmorabit** [lofar-astron/prefactor#131]
I'm running into an issue when I try to run the following command (via a shell script that submits a slurm job):

genericpipeline.py -d -c generic.cfg Pre-Facet-Calibrator.parset

The output error I get is this:
/system/software/linux-x86_64/LOFAR/2_20/lib/python2.7/site-packages/lofarpipe/support/utilities.pyc : Using default subprocess module!
QPID support NOT enabled! Will NOT connect to any broker, and messages will be lost!
Reading configuration file: generic.cfg
***** Exception occurred with no log handlers
***** ['${LOFARROOT}/share/pipeline/tasks.cfg'] is an invalid value for FileList task_files
Traceback (most recent call last):
  File "/system/software/linux-x86_64/LOFAR/2_20/lib/python2.7/site-packages/lofarpipe/cuisine/WSRTrecipe.py", line 132, in run
    status = self.go()
  File "/system/software/linux-x86_64/LOFAR/2_20/bin/genericpipeline.py", line 97, in go
    return super(GenericPipeline, self).go()
  File "/system/software/linux-x86_64/LOFAR/2_20/lib/python2.7/site-packages/lofarpipe/support/control.py", line 129, in go
    super(control, self).go()
  File "/system/software/linux-x86_64/LOFAR/2_20/lib/python2.7/site-packages/lofarpipe/support/stateful.py", line 91, in go
    super(StatefulRecipe, self).go()
  File "/system/software/linux-x86_64/LOFAR/2_20/lib/python2.7/site-packages/lofarpipe/support/baserecipe.py", line 221, in go
    self.config.get('DEFAULT', "task_files")
  File "/system/software/linux-x86_64/LOFAR/2_20/lib/python2.7/site-packages/lofarpipe/support/lofaringredient.py", line 252, in __setitem__
    (str(value), type(field).__name__, key)
TypeError: ['${LOFARROOT}/share/pipeline/tasks.cfg'] is an invalid value for FileList task_files
No results

I have attached my configuration file and the top part of the parset that describes the setup.

[parset_setup.txt](https://github.com/lofar-astron/prefactor/files/964043/parset_setup.txt)
[configuration.txt](https://github.com/lofar-astron/prefactor/files/964046/configuration.txt)

**Comment by AHorneffer** [comment]
```
[DEFAULT]
lofarroot = ${LOFARROOT}
```

I'm not sure that you can use environment variables in the pipeline config. And the error message doesn't look like it expanded `${LOFARROOT}` into an actual path. Have you tried putting the actual path - instead of the variable - there? (Same for `${HOME}`.)

**Comment by lmorabit** [comment]
That fixed the problem, thanks!
