### ISSUE TITLE
strange syntax error in fit_clocktec_initialguess_losoto.py

### ISSUE THREAD

**Issue by amisk** [lofar-astron/prefactor#159]
Hi,

I have a strange error.

> A fatal error has occured during the function execution
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/ppworker.py", line 80, in run
>     __fname, __fobjs = self.t.creceive(preprocess)
>   File "/usr/local/lib/python2.7/dist-packages/pptransport.py", line 115, in creceive
>     self.rcache[hash1] = map(preprocess, (msg, ))[0]
>   File "/usr/local/lib/python2.7/dist-packages/ppworker.py", line 51, in preprocess
>     fobjs = [compile(fsource, '<string>', 'exec') for fsource in fsources]
>   File "<string>", line 1668
>     print 'Number of filtered out data points:',  len(freq_old)-len(freq)
>                                               ^
> SyntaxError: invalid syntax
> None sdfasfasfasdf
> 
> 2017-11-24 17:19:51 WARNING node.slurm15.executable_args.h5imp_cal_losoto.h5: /opt/soft/lofar-stuff/prefactor/scripts/fit_clocktec_initialguess_losoto.py stderr: Traceback (most recent call last):
>   File "/opt/soft/lofar-stuff/prefactor/scripts/fit_clocktec_initialguess_losoto.py", line 412, in <module>
>     clockfit[start_time_id+i]  = fitresult[0]
> TypeError: 'NoneType' object has no attribute '__getitem__'
> Closing remaining open files:./h5imp_cal_losoto.h5...done

I have no idea what the reason might be, because on another machine, using the same software installation, the same prefactor version, the same parsets, everything runs fine. The only thing that would come to mind is that some required system package has a different version... but I can not figure out which one.

Any ideas?
Thanks.

**Comment by amisk** [comment]
Never mind. Please close.

Somebody tampered with the library and added a modified version of python-pp, which for whatever reason interferes with this script.
