### ISSUE TITLE
genericpipeline crashed with Error 104, connection reset by peer

### ISSUE THREAD

**Issue by amisk** [lofar-astron/prefactor#160]
Hi,

I cant get the pipeling to finish on three different machines. The lofar software is up to date on all of them. After 2 hours or so I always get a lot of errors like

2017-11-28 20:20:16 DEBUG   genericpipeline.executable_args: Failed to get recipe arguments from server: [Errno 104] Connection reset by peer
2017-11-28 20:20:23 WARNING genericpipeline.executable_args: socket.error: [Errno 104] Connection reset by peer
2017-11-28 20:23:57 DEBUG   genericpipeline.executable_args: Failed to get recipe arguments from server: [Errno 104] Connection reset by peer
2017-11-28 20:24:11 DEBUG   genericpipeline.executable_args: Failed to get recipe arguments from server: [Errno 104] Connection reset by peer

I noticed that at the end the memory is maxed out, but the first errors appear well before that...
I tried reducing the thread and process counts, but I have no idea what is happening ...
Any ideas?
Thx.

**Comment by amisk** [comment]
Nobody?

**Comment by twshimwell** [comment]
Can you put the entire log somewhere?

**Comment by amisk** [comment]
There you go.

http://www.miskolczi.de/pipeline.log

**Comment by twshimwell** [comment]
Is this the full log where the pipeline actually ends?

Did you check if the instrument tables look normal?

**Comment by amisk** [comment]
Yes, as far as I can tell. This is actually the log from Stefan.

I do not think that it has something to do with the data. We have this issue on all machines running the newest prefactor and with multiple measurement sets.

**Comment by twshimwell** [comment]
Odd because one of the final lines is "Subprocess completed with exit status 0" and there are not instances of the word error which it normally likes to write out when it fails.

**Comment by amisk** [comment]
I am running it now with 8 instead of 24 num_proc_per_node. Actually the machine has 16 cores. But it has 192 GB of ram, I actually thought that should be enough for the calibrators.
http://miskolczi.de/output.log
Here is the complete terminal output. At one point it starts throwing MemoryExceptions. Maybe it is indeed just a memory error. I now wrote a wrapping script that starts "dstat" while the pipeline is running, this will show me all the important system stats like cpu load, free memory, free swap, open sockets and so on. Lets see if this fixes it...

**Comment by amisk** [comment]
It's probably really a memory problem, but still. I've reduced the num_proc_per_node, num_proc_per_node_limit, max_dppp_threads to 4,4,2 and the 200 GB are still filled up for the calibrator pipeline. I remember that a couple of versions ago I was able to run this pipeline in 18 hours without the ram beeing filled up.

**Comment by amisk** [comment]
h5imp_cal actually crashed with:

Traceback (most recent call last):
  File "/opt/soft/lofar-stuff/lib/python2.7/site-packages/lofarpipe/support/remotecommand.py", line 295, in dispatch
    job_successful = (pg.wait_for_finish() is None)
  File "/opt/soft/lofar-stuff/lib/python2.7/site-packages/lofarpipe/support/subprocessgroup.py", line 237, in wait_for_finish
    fd_lookup[fileno].read(fileno)
  File "/opt/soft/lofar-stuff/lib/python2.7/site-packages/lofarpipe/support/subprocessgroup.py", line 110, in read
    self._addoutput(self.STDERR, self.process.stderr.read(4096))
IOError: [Errno 11] Resource temporarily unavailable

Restarting the pipeline, and therefore restarting h5impcal actually finished...
