### ISSUE TITLE
Error in the losotoImporter.py task

### ISSUE THREAD

**Issue by nudomarinero** [lofar-astron/prefactor#2]
The first time that the task is run I always get a ```Wrong HDF5``` format error.

I tried to run the task out of the pipeline to find out what the error was (is there any other way to debug a problem in the pipeline?). I got the following trace:
```
CRITICAL:root:Wrong HDF5 format for test.h5.
Traceback (most recent call last):
  File "../../prefactor/bin/losotoImporter.py", line 471, in <module>
    h5parmDB = h5parm(hdf5File, readonly = False)
  File "/usr/local/lib/python2.7/dist-packages/losoto/h5parm.py", line 31, in __init__
    raise Exception('Wrong HDF5 format for '+h5parmFile+'.')
Exception: Wrong HDF5 format for test.h5.
```

I have been tweaking a bit the code and now I am able to make it work the second time that I run the task, but have not been able to isolate the problem yet. Any idea?

**Comment by nudomarinero** [comment]
This is the exact error raised by the pipeline the first time:
```
Reading task definition file(s): /opt/LofIm-2_15/share/pipeline/tasks.cfg
2016-03-09 20:06:26 ERROR   node.ip-172-31-14-182.python_plugin: Wrong HDF5 format for ./h5imp_cal_losoto.h5.
2016-03-09 20:06:26 WARNING genericpipeline.executable_args: Remote command stderr: /opt/LofIm-2_15/lib/python2.7/site-packages/lofarpipe/support/utilities.pyc : Using default subprocess module!
/opt/LofIm-2_15/lib/python2.7/site-packages/lofar/parmdb/__init__.py:22: RuntimeWarning: to-Python converter for std::vector<double, std::allocator<double> > already registered; second conversion method ignored.
  from _parmdb import ParmDB
/opt/LofIm-2_15/lib/python2.7/site-packages/lofar/parmdb/__init__.py:22: RuntimeWarning: to-Python converter for std::vector<std::string, std::allocator<std::string> > already registered; second conversion method ignored.
  from _parmdb import ParmDB
CRITICAL:root:Wrong HDF5 format for ./h5imp_cal_losoto.h5.
ERROR:node.ip-172-31-14-182.python_plugin:Wrong HDF5 format for ./h5imp_cal_losoto.h5.
INFO:node.ip-172-31-14-182.python_plugin:Total time 101.5192s; user time: 97.6882s; system time: 4.9053s
DEBUG:node.ip-172-31-14-182.python_plugin:Start time was 1457553884.6402s; end time was 1457553986.1595s
Closing remaining open files:./h5imp_cal_losoto.h5...done
```
The second time it works:
```
Reading task definition file(s): /opt/LofIm-2_15/share/pipeline/tasks.cfg
2016-03-09 20:09:44 WARNING genericpipeline.executable_args: Remote command stderr: /opt/LofIm-2_15/lib/python2.7/site-packages/lofarpipe/support/utilities.pyc : Using default subprocess module!
/opt/LofIm-2_15/lib/python2.7/site-packages/lofar/parmdb/__init__.py:22: RuntimeWarning: to-Python converter for std::vector<double, std::allocator<double> > already registered; second conversion method ignored.
  from _parmdb import ParmDB
/opt/LofIm-2_15/lib/python2.7/site-packages/lofar/parmdb/__init__.py:22: RuntimeWarning: to-Python converter for std::vector<std::string, std::allocator<std::string> > already registered; second conversion method ignored.
  from _parmdb import ParmDB
WARNING:root:Appending to ./h5imp_cal_losoto.h5.
WARNING:root:Solution-set sol000 already present. Switching to default.
WARNING:root:Appending to ./h5imp_cal_losoto.h5.
INFO:node.ip-172-31-14-182.python_plugin:Total time 104.5529s; user time: 100.7620s; system time: 4.8971s
DEBUG:node.ip-172-31-14-182.python_plugin:Start time was 1457554079.8878s; end time was 1457554184.4409s
Closing remaining open files:./h5imp_cal_losoto.h5...done./h5imp_cal_losoto.h5...done
```

**Comment by nudomarinero** [comment]
The problem should be solved with the pull request #3 
I will also commit an update to losoto so ```del``` works OK but, until them, this should suffice.

**Comment by AHorneffer** [comment]
Race conditions, everybodies favourite kind of error. :-)

Thanks for solving it.

**Comment by twshimwell** [comment]
Hmmm, after this alteration to using close rather than del I have the error:

ERROR:node.para37.strw.leidenuniv.nl.python_plugin:h5parm instance has no attribute 'close'

If I go back to del it works on mine...

**Comment by nudomarinero** [comment]
This is probably caused by an old version of losoto. 
Could you find which version of losoto is installed in your system?

**Comment by twshimwell** [comment]
Ah ok. Thanks. I'll update that. It is quite old (May 2015)
