### ISSUE TITLE
Pipeline crash AFTER finishing succesfully??

### ISSUE THREAD

**Issue by amisk** [lofar-astron/prefactor#233]
Hey,

I have a weird one here ...
I am using the Target pipeline on a calibrator, to create a skymodel from that.
After the pipeline finishes succesfully, I get a crash.
```
2019-04-08 20:33:01 INFO    genericpipeline: LOFAR Pipeline finished succesfully.
2019-04-08 20:33:01 INFO    genericpipeline: recipe genericpipeline completed
Results:
Process PoolWorker-19:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 270, in _bootstrap
    util._exit_function()
  File "/usr/lib/python2.7/multiprocessing/util.py", line 308, in _exit_function
    _run_finalizers(0)
  File "/usr/lib/python2.7/multiprocessing/util.py", line 250, in _run_finalizers
    def _run_finalizers(minpriority=None):
TypeError: set() takes exactly 1 argument (3 given)
```
All the resulting files are there, so I think it really completed everything correct.
I assume there is something wrong when closing the subprocess?

**Comment by sarrvesh** [comment]
I got the same thing. While running genericpipeline with the -vd flags, I got 

> Results:
Process PoolWorker-23:
Process PoolWorker-2:
Process PoolWorker-7:
Process PoolWorker-3:
Process PoolWorker-9:
Process PoolWorker-15:
Process PoolWorker-6:
Process PoolWorker-1:
Traceback (most recent call last):
Process PoolWorker-8:
Process PoolWorker-21:
  File "/usr/lib/python2.7/multiprocessing/process.py", line 270, in _bootstrap
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 270, in _bootstrap
Process PoolWorker-17:
Process PoolWorker-24:
Process PoolWorker-11:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Process PoolWorker-5:
Process PoolWorker-10:
Process PoolWorker-18:
  File "/usr/lib/python2.7/multiprocessing/process.py", line 270, in _bootstrap
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Process PoolWorker-20:
  File "/usr/lib/python2.7/multiprocessing/process.py", line 270, in _bootstrap
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 270, in _bootstrap
Traceback (most recent call last):
Traceback (most recent call last):
Process PoolWorker-12:
Traceback (most recent call last):
Process PoolWorker-14:
Process PoolWorker-19:
Process PoolWorker-13:
Traceback (most recent call last):
Traceback (most recent call last):
Process PoolWorker-22:
Process PoolWorker-16:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 270, in _bootstrap
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 270, in _bootstrap
  File "/usr/lib/python2.7/multiprocessing/process.py", line 270, in _bootstrap
  File "/usr/lib/python2.7/multiprocessing/process.py", line 270, in _bootstrap
  File "/usr/lib/python2.7/multiprocessing/process.py", line 270, in _bootstrap
  File "/usr/lib/python2.7/multiprocessing/process.py", line 270, in _bootstrap
Process PoolWorker-4:
  File "/usr/lib/python2.7/multiprocessing/process.py", line 270, in _bootstrap
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 270, in _bootstrap
  File "/usr/lib/python2.7/multiprocessing/process.py", line 270, in _bootstrap
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 270, in _bootstrap
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 270, in _bootstrap
  File "/usr/lib/python2.7/multiprocessing/process.py", line 270, in _bootstrap
  File "/usr/lib/python2.7/multiprocessing/process.py", line 270, in _bootstrap
  File "/usr/lib/python2.7/multiprocessing/process.py", line 270, in _bootstrap
  File "/usr/lib/python2.7/multiprocessing/process.py", line 270, in _bootstrap
  File "/usr/lib/python2.7/multiprocessing/process.py", line 270, in _bootstrap
  File "/usr/lib/python2.7/multiprocessing/process.py", line 270, in _bootstrap
  File "/usr/lib/python2.7/multiprocessing/process.py", line 270, in _bootstrap
  File "/usr/lib/python2.7/multiprocessing/process.py", line 270, in _bootstrap
    util._exit_function()
    util._exit_function()
    util._exit_function()
  File "/usr/lib/python2.7/multiprocessing/util.py", line 297, in _exit_function
    util._exit_function()
  File "/usr/lib/python2.7/multiprocessing/util.py", line 297, in _exit_function
  File "/usr/lib/python2.7/multiprocessing/util.py", line 297, in _exit_function
    util._exit_function()
    util._exit_function()
    util._exit_function()
  File "/usr/lib/python2.7/multiprocessing/util.py", line 297, in _exit_function
    util._exit_function()
    util._exit_function()
    util._exit_function()
  File "/usr/lib/python2.7/multiprocessing/util.py", line 297, in _exit_function
    util._exit_function()
    util._exit_function()
    util._exit_function()
    util._exit_function()
    util._exit_function()
  File "/usr/lib/python2.7/multiprocessing/util.py", line 297, in _exit_function
    util._exit_function()
  File "/usr/lib/python2.7/multiprocessing/util.py", line 297, in _exit_function
  File "/usr/lib/python2.7/multiprocessing/util.py", line 297, in _exit_function
    util._exit_function()
    util._exit_function()
  File "/usr/lib/python2.7/multiprocessing/util.py", line 297, in _exit_function
  File "/usr/lib/python2.7/multiprocessing/util.py", line 297, in _exit_function
    util._exit_function()
    util._exit_function()
File "/usr/lib/python2.7/multiprocessing/util.py", line 297, in _exit_function
    util._exit_function()
  File "/usr/lib/python2.7/multiprocessing/util.py", line 297, in _exit_function
  File "/usr/lib/python2.7/multiprocessing/util.py", line 297, in _exit_function
  File "/usr/lib/python2.7/multiprocessing/util.py", line 297, in _exit_function
  File "/usr/lib/python2.7/multiprocessing/util.py", line 297, in _exit_function
  File "/usr/lib/python2.7/multiprocessing/util.py", line 297, in _exit_function
  File "/usr/lib/python2.7/multiprocessing/util.py", line 297, in _exit_function
  File "/usr/lib/python2.7/multiprocessing/util.py", line 297, in _exit_function
  File "/usr/lib/python2.7/multiprocessing/util.py", line 297, in _exit_function
  File "/usr/lib/python2.7/multiprocessing/util.py", line 297, in _exit_function
  File "/usr/lib/python2.7/multiprocessing/util.py", line 297, in _exit_function
    def _exit_function(info=info, debug=debug, _run_finalizers=_run_finalizers,
    def _exit_function(info=info, debug=debug, _run_finalizers=_run_finalizers,
TypeError: set() takes exactly 1 argument (3 given)
    def _exit_function(info=info, debug=debug, _run_finalizers=_run_finalizers,
TypeError: set() takes exactly 1 argument (3 given)
    def _exit_function(info=info, debug=debug, _run_finalizers=_run_finalizers,
    def _exit_function(info=info, debug=debug, _run_finalizers=_run_finalizers,
    def _exit_function(info=info, debug=debug, _run_finalizers=_run_finalizers,
    def _exit_function(info=info, debug=debug, _run_finalizers=_run_finalizers,
    def _exit_function(info=info, debug=debug, _run_finalizers=_run_finalizers,
    def _exit_function(info=info, debug=debug, _run_finalizers=_run_finalizers,
TypeError: set() takes exactly 1 argument (3 given)
TypeError: set() takes exactly 1 argument (3 given)
TypeError: set() takes exactly 1 argument (3 given)
TypeError: set() takes exactly 1 argument (3 given)
TypeError: set() takes exactly 1 argument (3 given)
    def _exit_function(info=info, debug=debug, _run_finalizers=_run_finalizers,
    def _exit_function(info=info, debug=debug, _run_finalizers=_run_finalizers,
TypeError: set() takes exactly 1 argument (3 given)
TypeError: set() takes exactly 1 argument (3 given)
TypeError: set() takes exactly 1 argument (3 given)
    def _exit_function(info=info, debug=debug, _run_finalizers=_run_finalizers,
    def _exit_function(info=info, debug=debug, _run_finalizers=_run_finalizers,
    def _exit_function(info=info, debug=debug, _run_finalizers=_run_finalizers,
TypeError: set() takes exactly 1 argument (3 given)
    def _exit_function(info=info, debug=debug, _run_finalizers=_run_finalizers,
TypeError: set() takes exactly 1 argument (3 given)
TypeError: set() takes exactly 1 argument (3 given)
    def _exit_function(info=info, debug=debug, _run_finalizers=_run_finalizers,
TypeError: set() takes exactly 1 argument (3 given)
    def _exit_function(info=info, debug=debug, _run_finalizers=_run_finalizers,
TypeError: set() takes exactly 1 argument (3 given)
    def _exit_function(info=info, debug=debug, _run_finalizers=_run_finalizers,
    def _exit_function(info=info, debug=debug, _run_finalizers=_run_finalizers,
    def _exit_function(info=info, debug=debug, _run_finalizers=_run_finalizers,
TypeError: set() takes exactly 1 argument (3 given)
TypeError: set() takes exactly 1 argument (3 given)
TypeError: set() takes exactly 1 argument (3 given)
TypeError: set() takes exactly 1 argument (3 given)
    def _exit_function(info=info, debug=debug, _run_finalizers=_run_finalizers,
    def _exit_function(info=info, debug=debug, _run_finalizers=_run_finalizers,
TypeError: set() takes exactly 1 argument (3 given)
TypeError: set() takes exactly 1 argument (3 given)
TypeError: set() takes exactly 1 argument (3 given)
    def _exit_function(info=info, debug=debug, _run_finalizers=_run_finalizers,
    def _exit_function(info=info, debug=debug, _run_finalizers=_run_finalizers,
TypeError: set() takes exactly 1 argument (3 given)
TypeError: set() takes exactly 1 argument (3 given)
Closing remaining open files:/home/sarrvesh/Oct_2017/runtime//Pre-Facet-Target/results/cal_values/solutions.h5...done

**Comment by rvweeren** [comment]
I've seen this as well, output is fine though
