### ISSUE TITLE
gaierror: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by tikk3r** [lofar-astron/prefactor#268]
While testing my Ubunut 18.04 based Singularity containers, I now run into the error below when running prefactor. Perhaps it's more of a genericpipeline issue, but I don't see this in my CentOS based images. My build procedure is the same and I didn't encounter any obvious errors or warnings during build either.

Has someone seen this before or do they know where to look on how to fix this?

```
2020-04-22 12:39:32 DEBUG   genericpipeline: Pipeline start time: 2020-04-22T10:39:32
2020-04-22 12:39:32 INFO    genericpipeline: LOFAR Pipeline (Pre-Facet-Target) starting.
2020-04-22 12:39:32 INFO    genericpipeline: SASID = , MOMID = , Feedback method = none
NYI: validate_steps
2020-04-22 12:39:32 INFO    genericpipeline: Beginning step createmap_target
2020-04-22 12:39:32 INFO    genericpipeline: Beginning step get_targetname
Successful readonly open of default-locked table /tmp/tmp.zKEunv7Njv/Input/L686962_SB001_uv.MS::OBSERVATION: 31 columns, 1 rows
2020-04-22 12:39:33 INFO    genericpipeline: Beginning step combine_data_target_map
FILE:  ['/tmp/tmp.zKEunv7Njv/Input/L686962_SB001_uv.MS']
2020-04-22 12:39:33 INFO    genericpipeline: Beginning step check_Ateam_separation
2020-04-22 12:39:33 INFO    genericpipeline: Running task: pythonplugin
2020-04-22 12:39:33 INFO    genericpipeline.executable_args: recipe executable_args started
2020-04-22 12:39:33 INFO    genericpipeline.executable_args: Starting /project/sksp/Software/prefactor/scripts/check_Ateam_separation.py run
2020-04-22 12:39:33 DEBUG   genericpipeline.executable_args: Pipeline start time: 2020-04-22T10:39:32
2020-04-22 12:39:33 INFO    genericpipeline.executable_args: Limiting to 1 simultaneous jobs/node
2020-04-22 12:39:33 ERROR   genericpipeline.executable_args: Exception caught: [Errno -2] Name or service not known
Traceback (most recent call last):
  File "/opt/lofar/lofar/lib/python2.7/site-packages/lofarpipe/cuisine/WSRTrecipe.py", line 132, in run
    status = self.go()
  File "/opt/lofar/lofar/lib64/python2.7/site-packages/lofarpipe/recipes/master/executable_args.py", line 387, in go
    self._schedule_jobs(jobs, max_per_node)
  File "/opt/lofar/lofar/lib/python2.7/site-packages/lofarpipe/support/remotecommand.py", line 572, in _schedule_jobs
    with job_server(self.logger, jobpool, self.error) as (jobhost, jobport):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/opt/lofar/lofar/lib/python2.7/site-packages/lofarpipe/support/jobserver.py", line 169, in job_server
    jobserver = JobSocketReceiver(logger, jobpool, error, port=0)
  File "/opt/lofar/lofar/lib/python2.7/site-packages/lofarpipe/support/jobserver.py", line 113, in __init__
    SocketServer.ThreadingTCPServer.__init__(self, (host, port), JobStreamHandler)
  File "/usr/lib/python2.7/SocketServer.py", line 420, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/SocketServer.py", line 434, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
gaierror: [Errno -2] Name or service not known
2020-04-22 12:39:33 WARNING genericpipeline: pythonplugin reports failure (using executable_args recipe)
2020-04-22 12:39:33 ERROR   genericpipeline: *******************************************
2020-04-22 12:39:33 ERROR   genericpipeline: Failed pipeline run: Pre-Facet-Target
2020-04-22 12:39:33 ERROR   genericpipeline: Detailed exception information:
2020-04-22 12:39:33 ERROR   genericpipeline: <class 'lofarpipe.support.lofarexceptions.PipelineRecipeFailed'>
2020-04-22 12:39:33 ERROR   genericpipeline: pythonplugin failed
2020-04-22 12:39:33 ERROR   genericpipeline: *******************************************
2020-04-22 12:39:33 ERROR   genericpipeline: LOFAR Pipeline finished unsuccesfully.
2020-04-22 12:39:33 WARNING genericpipeline: recipe genericpipeline completed with errors
```

**Comment by tikk3r** [comment]
@AlexKurek I've been updating to Ubuntu as well. Have you encountered this with your images?

**Comment by adrabent** [comment]
@tikk3r 
I would agree that it looks like a genericpipeline issue. Do you run the "local" mode or have you specified running it with slurm? It seems to me that it does not find a socket to submit the job requests to and thus fails.

**Comment by AlexKurek** [comment]
@tikk3r,
No, there was a lot of errors, but not this one

**Comment by tikk3r** [comment]
@adrabent it's running on local mode. The job calls genericpipeline.py on the node itself. Its configuration file is here: https://github.com/apmechev/GRID_Sandbox/blob/prefactor_spider/sing_pipeline.cfg

**Comment by adrabent** [comment]
I guess there we will need to check the code in detail. In a working example the job dispatcher launches at localhost (127.0.0.1) or at the node itself (like her lof009 on CEP):

`genericpipeline.executable_args: Job dispatcher at 10.144.5.111:58302`

It uses a high-order port numbers on the local machine. Maybe a firewall or something else in the image is preventing the genericpipeline from accessing it.

**Comment by tikk3r** [comment]
I see the same high port numbers in my runs using my old container
`2020-04-22 11:50:49 DEBUG   genericpipeline.executable_args: Job dispatcher at 10.0.0.7:54288`

Poking around a bit I found https://stackoverflow.com/questions/38254394/name-or-service-not-known
and discovered that /etc/hostname differs from what `echo $HOSTNAME` and `hostname` return. Maybe that is the cause of conflict. I've removed /etc/hostname and am checking to see if that fixes it.

**Comment by tikk3r** [comment]
Hmm that did not help either. Very puzzling error this.

**Comment by tikk3r** [comment]
So it works in Leiden, but not on surfsara. Interesting.

**Comment by tikk3r** [comment]
Alright, I'll close this issue here as it is not a prefactor problem. Something is funky with the Ubuntu installation in my container.
